extends:
  - airbnb-base
  - plugin:import/errors
  - prettier
plugins:
  - import
  - prettier
rules:
  no-underscore-dangle:
    - error
    - allow: [_id]
  prettier/prettier:
    - error
    - semi: true
      singleQuote: true
      bracketSpacing: true
      trailingComma: all
